name: Haskell CI

on:
  push:
    branches: ["master"]
    paths-ignore:
      - "**/*.txt"
  pull_request:
    branches: ["master"]
    paths-ignore:
      - "**/*.txt"

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Haskell
        uses: haskell/actions/setup@v2
        with:
          ghc-version: "9.4.8"
          cabal-version: "3.6"

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libssl-dev

      - name: Cache Cabal
        uses: actions/cache@v3
        env:
          cache-name: cache-cabal
        with:
          path: ~/.cabal/store
          key: ${{ runner.os }}-cabal-store-${{ hashFiles('**/*.cabal') }}-${{ hashFiles('**/cabal.project') }}
          restore-keys: |
            ${{ runner.os }}-cabal-store-

      - name: Install dependencies
        run: |
          cabal update
          cabal install hspec-discover --overwrite-policy=always
          cabal build --only-dependencies --enable-tests --enable-benchmarks

      - name: Build
        run: cabal build --enable-tests --enable-benchmarks all

      - name: Run tests
        run: cabal test all --test-show-details=always
